import os
import sys
import subprocess

REMOVE_PATHS = [
{% if cookiecutter.use_lambda != 'y' -%}
'runtime/app.py',
'runtime',
'tests/unit/runtime/test_handler.py',
'tests/unit/runtime',
'tests/unit/runtime/events/event_api_1.json',
'tests/unit/runtime/events',
{%- endif %}
]

for path in REMOVE_PATHS:
    path = path.strip()
    if path and os.path.exists(path):
        if os.path.isdir(path):
            os.rmdir(path)
        else:
            os.unlink(path)



subprocess.call(['git', 'init'])
subprocess.call(['git', 'add', '.gitignore'])
subprocess.call(['git', 'add', '*'])
subprocess.call(['git', 'commit', '-m', 'generated by cookiecutter'])