import os
import shlex
import subprocess

# remove direcotires and files when lambda is not used
REMOVE_PATHS = [
    {% if cookiecutter.use_lambda != 'y' -%}
    "runtime/app.py",
    "runtime",
    "tests/unit/runtime/test_handler.py",
    "tests/unit/runtime/events/event_api_1.json",
    "tests/unit/runtime/events",
    "tests/unit/runtime",
    {%- endif %}
]

for path in REMOVE_PATHS:
    path = path.strip()
    if path and os.path.exists(path):
        if os.path.isdir(path):
            os.rmdir(path)
        else:
            os.unlink(path)

# fix the stack name in pipeline. it is in Jinja2 format, too much quoting needed
# to make it a template itself
# OSX and Linux sed has different syntax for inline editing so we use a intermediary file
# instead
with open(".github/workflows/pipeline.yaml", "w") as out_f:
    subprocess.call(
        shlex.split("sed 's/DUMMYSTACKNAME/{{ cookiecutter.stack_name }}/g' .github/workflows/pipeline.yaml.pre"),
        stdout=out_f,
    )
os.unlink(".github/workflows/pipeline.yaml.pre")


# create a git repo, everybody needs this, right?
subprocess.call(["git", "init"])
subprocess.call(["git", "add", ".gitignore"])
subprocess.call(["git", "add", "*"])
subprocess.call(["git", "commit", "-m", "generated by cookiecutter"])
